/* SPDX-FileCopyrightText: 2026 Logan Bissonnette
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */

/* PokéRogue biome map.
   Data comes from data.js (generated by build-data.mjs from the game sources). */
(() => {
  "use strict";

  const DATA = window.BIOME_MAP_DATA;
  const biomes = DATA.biomes;
  const byKey = new Map(biomes.map(b => [b.key, b]));

  // ------------------------------------------------------------ wanted Pokémon
  // The viewer's own list of species to keep an eye out for. data.js carries
  // every biome's wild pools and a catalog of every species, so the list can
  // be edited in the page; it is remembered in the browser and mirrored into
  // the URL hash (`#w=MEWTWO,GROUDON`) so a link can carry it.
  const catalog = new Map((DATA.species ?? []).map(s => [s.key, s]));
  const TIMES = ["DAWN", "DAY", "DUSK", "NIGHT"];
  const labelOf = key => DATA.labels?.[key.toLowerCase().replace(/_([a-z])/g, (_, c) => c.toUpperCase())] ?? key;
  const tierText = spot => `${labelOf(spot.tier)}${spot.boss ? " · boss waves only" : ""}`;
  const timesText = spot => (spot.times[0] === "ALL" ? "any time of day" : spot.times.map(labelOf).join(" & "));
  const spotSummary = spots => spots.map(s => `${tierText(s)}, ${timesText(s)}`).join(" / ");

  /** Every (biome, tier) a species sits in, with the live pool size per time of day. */
  function spotsFor(key) {
    const spots = [];
    for (const biome of biomes) {
      for (const [tier, byTime] of Object.entries(biome.pool ?? {})) {
        const times = Object.entries(byTime)
          .filter(([, list]) => list.includes(key))
          .map(([time]) => time);
        if (times.length === 0) {
          continue;
        }
        // The arena's live pool for a tier is ALL + the current time of day.
        const poolSizes = Object.fromEntries(
          TIMES.map(t => [t, new Set([...(byTime.ALL ?? []), ...(byTime[t] ?? [])]).size]),
        );
        spots.push({
          biome: biome.key,
          tier,
          boss: tier.startsWith("BOSS"),
          times: times.includes("ALL") ? ["ALL"] : TIMES.filter(t => times.includes(t)),
          tierChance: DATA.tierChance?.[tier],
          poolSizes,
          pool: biome.pool,
        });
      }
    }
    return spots;
  }

  function parseHash() {
    const raw = decodeURIComponent(location.hash.slice(1));
    if (!raw) {
      return {};
    }
    if (!raw.includes("=")) {
      return byKey.has(raw) ? { b: raw } : {};
    }
    const params = new URLSearchParams(raw);
    return { b: params.get("b") || undefined, w: params.get("w")?.split(",").filter(Boolean) };
  }

  const defaultWanted = (DATA.defaultWanted ?? []).filter(k => catalog.has(k));
  function loadWantedKeys() {
    const fromHash = parseHash().w;
    if (fromHash) {
      return fromHash.filter(k => catalog.has(k));
    }
    try {
      const saved = JSON.parse(localStorage.getItem("biome-map-wanted") ?? "null");
      if (Array.isArray(saved)) {
        return saved.filter(k => catalog.has(k));
      }
    } catch {
      // storage unavailable or corrupt; fall through to the defaults
    }
    return [...defaultWanted];
  }

  let wantedKeys = loadWantedKeys();
  /** @type {Array<object>} catalog entries plus their spots */
  let wanted = [];
  /** biome key -> [{ species, spots: [...] }] (one entry per species, all its tiers there) */
  let wantedByBiome = new Map();
  function rebuildWanted() {
    wanted = wantedKeys.map(key => ({ ...catalog.get(key), spots: spotsFor(key) }));
    wantedByBiome = new Map();
    for (const species of wanted) {
      for (const spot of species.spots) {
        if (!wantedByBiome.has(spot.biome)) {
          wantedByBiome.set(spot.biome, []);
        }
        const list = wantedByBiome.get(spot.biome);
        let entry = list.find(e => e.species === species);
        if (!entry) {
          entry = { species, spots: [] };
          list.push(entry);
        }
        entry.spots.push(spot);
      }
    }
  }
  rebuildWanted();

  /** The species' icon, cut from its atlas as a CSS sprite. */
  function iconHtml(species, scale = 1) {
    const ic = species.icon;
    const atlas = ic && DATA.atlases?.[ic[0]];
    if (!atlas) {
      return `<span class="picon missing">?</span>`;
    }
    const [, x, y, w, h] = ic;
    const style = [
      `width:${w * scale}px`,
      `height:${h * scale}px`,
      `background-image:url(${atlas.file})`,
      `background-position:-${x * scale}px -${y * scale}px`,
      `background-size:${atlas.w * scale}px ${atlas.h * scale}px`,
    ].join(";");
    return `<span class="picon pixel" style="${style}"></span>`;
  }

  function badgesHtml(biomeKey) {
    const here = wantedByBiome.get(biomeKey);
    if (!here) {
      return "";
    }
    return `<span class="badges">${here
      .map(
        ({ species, spots }) =>
          `<span class="chip" title="${species.name}: ${spotSummary(spots)}">${iconHtml(species)}</span>`,
      )
      .join("")}</span>`;
  }

  // ------------------------------------------------------------ layout
  // Hand-placed grid positions (column, row). Roughly left-to-right by how
  // far from Town a biome is, with themed regions: urban along the top,
  // grassland through the middle, water along the bottom, rock/dark to the east.
  const GRID = {
    TOWN: [0, 3],
    PLAINS: [1, 3],
    METROPOLIS: [2, 0],
    SLUM: [3, 0],
    CONSTRUCTION_SITE: [4, 0],
    POWER_PLANT: [5, 0],
    FACTORY: [6, 0],
    LABORATORY: [6.5, 1],
    DOJO: [4.5, 1],
    GRASS: [2, 2],
    TALL_GRASS: [3, 2],
    FOREST: [4, 2],
    JUNGLE: [5, 2],
    TEMPLE: [6, 2],
    MEADOW: [4, 3],
    FAIRY_CAVE: [5, 3],
    DESERT: [6, 3],
    RUINS: [7, 3],
    CAVE: [4, 4],
    BADLANDS: [5, 4],
    MOUNTAIN: [6, 4],
    SPACE: [7, 4],
    SWAMP: [2, 5],
    GRAVEYARD: [4, 5],
    ABYSS: [5, 5],
    WASTELAND: [6, 5],
    VOLCANO: [7, 5],
    LAKE: [2, 6],
    BEACH: [3, 6],
    SEA: [4, 6],
    SEABED: [5, 6],
    ICE_CAVE: [6, 6],
    SNOWY_FOREST: [7, 6],
    ISLAND: [3, 7],
    END: [8, 3],
  };
  const COL = 168;
  const ROW = 114;
  const PAD = 36;
  const NODE_W = 108;
  const NODE_H = 85;

  // Any biome the game adds later that has no hand position gets a free slot
  // in the column matching its depth, so the page never breaks.
  const taken = new Set(Object.values(GRID).map(([c, r]) => `${c},${r}`));
  const positions = new Map();
  let maxCol = 0;
  let maxRow = 0;
  for (const biome of biomes) {
    let cell = GRID[biome.key];
    if (!cell) {
      const col = Math.min(biome.depth ?? 8, 8);
      let row = 0;
      while (taken.has(`${col},${row}`)) {
        row++;
      }
      cell = [col, row];
      taken.add(`${col},${row}`);
    }
    const x = PAD + cell[0] * COL;
    const y = PAD + cell[1] * ROW;
    positions.set(biome.key, { x, y, cx: x + NODE_W / 2, cy: y + NODE_H / 2 });
    maxCol = Math.max(maxCol, cell[0]);
    maxRow = Math.max(maxRow, cell[1]);
  }
  const MAP_W = PAD * 2 + maxCol * COL + NODE_W;
  const MAP_H = PAD * 2 + maxRow * ROW + NODE_H;

  // ------------------------------------------------------------ state
  const state = {
    mode: "map", // "map" (holding a Map item, the default) | "random" (no Map, the game picks)
    showLabels: true,
    selected: null,
    hovered: null,
    wantedHover: null,
    /** Side panel mode: "info" shows the intro / selected biome, "planner" the boss planner. */
    panel: "info",
    /** A highlighted route: [{ key, label }] in travel order, or null. */
    path: null,
    planner: { wave: 1, biome: "TOWN", gym: "20", luck: 0, lures: 0, endless: false, option: null },
    view: { x: 0, y: 0, k: 1 },
  };

  const $ = sel => document.querySelector(sel);
  const viewport = $("#viewport");
  const map = $("#map");
  const svg = $("#edges");
  const panel = $("#panel");
  const tableBody = $("#routes-body");

  map.style.width = `${MAP_W}px`;
  map.style.height = `${MAP_H}px`;
  svg.setAttribute("width", MAP_W);
  svg.setAttribute("height", MAP_H);

  // ------------------------------------------------------------ helpers
  const pct = p => {
    const v = p * 100;
    return `${Number.isInteger(Math.round(v * 10) / 10) ? Math.round(v) : v.toFixed(1)}%`;
  };
  const chance = link => (state.mode === "map" ? link.pOffered : link.p);
  const rollText = (link, linkCount) =>
    linkCount === 1 ? "only exit" : link.weight === 1 ? "always an option" : `1 in ${link.weight} roll`;

  function earliestWave(biome) {
    if (biome.key === "END") {
      return "191 (Classic) / 50 (Daily)";
    }
    return biome.depth == null ? "—" : `${biome.depth * 10 + 1}`;
  }

  function incoming(key) {
    const list = [];
    for (const src of biomes) {
      for (const link of src.links) {
        if (link.to === key) {
          list.push({ from: src, link });
        }
      }
    }
    return list;
  }

  // Card thumbnails only show the backdrop; the side panel layers the two
  // battle platforms (`_b` enemy side, `_a` player side) on top like the game does.
  function thumbHtml(biome) {
    const a = biome.art;
    return `<span class="thumb pixel">${a.bg ? `<img src="${a.bg}" alt="">` : ""}</span>`;
  }

  // ------------------------------------------------------------ nodes
  const nodeEls = new Map();
  for (const biome of biomes) {
    const pos = positions.get(biome.key);
    const el = document.createElement("button");
    el.className = `node${biome.key === "END" ? " end" : ""}`;
    el.type = "button";
    el.dataset.key = biome.key;
    el.style.left = `${pos.x}px`;
    el.style.top = `${pos.y}px`;
    el.setAttribute("aria-label", `${biome.name}: ${biome.links.length} exit${biome.links.length === 1 ? "" : "s"}`);
    el.innerHTML = `${thumbHtml(biome)}<span class="name">${biome.name}</span>${badgesHtml(biome.key)}<span class="stage"></span>`;
    el.addEventListener("click", () => {
      if (!suppressClick) {
        select(biome.key === state.selected ? null : biome.key);
      }
    });
    el.addEventListener("pointerenter", () => setHover(biome.key));
    el.addEventListener("pointerleave", () => setHover(null));
    map.appendChild(el);
    nodeEls.set(biome.key, el);
  }

  // ------------------------------------------------------------ edges
  // Each edge is a quadratic curve. The bend is chosen from a few candidates
  // so the curve threads between cards instead of running across them.
  const SVG_NS = "http://www.w3.org/2000/svg";
  const edges = [];

  function rectOf(key, margin = 6) {
    const p = positions.get(key);
    return { x0: p.x - margin, y0: p.y - margin, x1: p.x + NODE_W + margin, y1: p.y + NODE_H + margin };
  }
  const inRect = (r, x, y) => x > r.x0 && x < r.x1 && y > r.y0 && y < r.y1;

  // Point where the ray from the card centre towards (tx,ty) leaves the card.
  function borderPoint(key, tx, ty, inset = 0) {
    const p = positions.get(key);
    const hw = NODE_W / 2 + inset;
    const hh = NODE_H / 2 + inset;
    const dx = tx - p.cx;
    const dy = ty - p.cy;
    if (dx === 0 && dy === 0) {
      return { x: p.cx, y: p.cy };
    }
    const scale = Math.min(hw / Math.abs(dx || 1e-9), hh / Math.abs(dy || 1e-9));
    return { x: p.cx + dx * scale, y: p.cy + dy * scale };
  }

  const quad = (a, c, b, t) => ({
    x: (1 - t) * (1 - t) * a.x + 2 * (1 - t) * t * c.x + t * t * b.x,
    y: (1 - t) * (1 - t) * a.y + 2 * (1 - t) * t * c.y + t * t * b.y,
  });

  function routeEdge(from, to) {
    const a = positions.get(from);
    const b = positions.get(to);
    const dx = b.cx - a.cx;
    const dy = b.cy - a.cy;
    const len = Math.hypot(dx, dy) || 1;
    const nx = -dy / len;
    const ny = dx / len;
    const obstacles = biomes.filter(o => o.key !== from && o.key !== to).map(o => rectOf(o.key));
    const base = Math.min(40 + len * 0.08, 90);
    const candidates = [0, base, -base, base * 2, -base * 2, base * 3, -base * 3, base * 4, -base * 4];
    let best = null;
    for (const off of candidates) {
      const ctrl = { x: (a.cx + b.cx) / 2 + nx * off, y: (a.cy + b.cy) / 2 + ny * off };
      let hits = 0;
      for (let i = 1; i < 24; i++) {
        const pt = quad({ x: a.cx, y: a.cy }, ctrl, { x: b.cx, y: b.cy }, i / 24);
        if (obstacles.some(r => inRect(r, pt.x, pt.y))) {
          hits++;
        }
      }
      const score = hits * 1000 + Math.abs(off);
      if (!best || score < best.score) {
        best = { off, ctrl, score };
      }
    }
    // Trim the curve so it starts/ends at the card borders (and leaves room for the arrowhead).
    const start = borderPoint(from, best.ctrl.x, best.ctrl.y, 2);
    const end = borderPoint(to, best.ctrl.x, best.ctrl.y, 7);
    return { start, ctrl: best.ctrl, end };
  }

  const nodeRects = biomes.map(b => rectOf(b.key, 2));
  const overlaps = (a, b) => a.x0 < b.x1 && a.x1 > b.x0 && a.y0 < b.y1 && a.y1 > b.y0;
  const LABEL_H = 16;

  // Labels sit *beside* their line, not on it, so arrows stay visible. Each
  // label tries a few spots along the curve on either side and keeps the one
  // clearest of cards and of labels placed before it (shorter links go first
  // so they keep the spot between their two cards).
  const LABEL_T = [0.5, 0.42, 0.58, 0.34, 0.66, 0.26, 0.74, 0.18, 0.82];
  function placeLabels() {
    const placed = [];
    const order = [...edges].sort((a, b) => a.length - b.length);
    for (const e of order) {
      const w = e.labelWidth;
      const { start, ctrl, end } = e.route;
      let best = null;
      for (const t of LABEL_T) {
        const p = quad(start, ctrl, end, t);
        // Unit normal of the curve at t, from its tangent.
        const tx = 2 * (1 - t) * (ctrl.x - start.x) + 2 * t * (end.x - ctrl.x);
        const ty = 2 * (1 - t) * (ctrl.y - start.y) + 2 * t * (end.y - ctrl.y);
        const tl = Math.hypot(tx, ty) || 1;
        const nx = -ty / tl;
        const ny = tx / tl;
        // Push the label's box just clear of the line whatever the line's angle.
        const push = 5 + Math.abs(nx) * (w / 2) + Math.abs(ny) * (LABEL_H / 2);
        for (const side of [1, -1]) {
          const cx = p.x + nx * push * side;
          const cy = p.y + ny * push * side;
          const r = { x0: cx - w / 2, y0: cy - LABEL_H / 2, x1: cx + w / 2, y1: cy + LABEL_H / 2 };
          const hits = nodeRects.filter(n => overlaps(r, n)).length * 100 + placed.filter(l => overlaps(r, l)).length * 10;
          const score = hits + Math.abs(t - 0.5) * 20 + (side < 0 ? 1 : 0);
          if (!best || score < best.score) {
            best = { cx, cy, r, score };
          }
        }
      }
      placed.push(best.r);
      e.text.setAttribute("x", best.cx);
      e.text.setAttribute("y", best.cy);
    }
  }

  const defs = document.createElementNS(SVG_NS, "defs");
  defs.innerHTML = `
    <marker id="arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse" markerUnits="userSpaceOnUse">
      <path d="M0,0 L10,5 L0,10 z" fill="context-stroke"></path>
    </marker>`;
  svg.appendChild(defs);

  const edgeLayer = document.createElementNS(SVG_NS, "g");
  svg.appendChild(edgeLayer);
  // Labels live in their own SVG stacked above the cards, so a label that has
  // to sit close to a card is never hidden underneath it.
  const labelSvg = document.createElementNS(SVG_NS, "svg");
  labelSvg.setAttribute("width", MAP_W);
  labelSvg.setAttribute("height", MAP_H);
  labelSvg.classList.add("labels");
  const labelLayer = document.createElementNS(SVG_NS, "g");
  labelSvg.appendChild(labelLayer);
  map.appendChild(labelSvg);

  for (const biome of biomes) {
    for (const link of biome.links) {
      const r = routeEdge(biome.key, link.to);
      const g = document.createElementNS(SVG_NS, "g");
      g.classList.add("edge");
      if (link.weight > 1 && biome.links.length > 1) {
        g.classList.add("rolled");
      }
      if (Math.hypot(positions.get(link.to).cx - positions.get(biome.key).cx, positions.get(link.to).cy - positions.get(biome.key).cy) > 420) {
        // Long hops (mostly loops back towards Plains) fade into the background until focused.
        g.classList.add("long");
      }
      const path = document.createElementNS(SVG_NS, "path");
      path.setAttribute("d", `M${r.start.x},${r.start.y} Q${r.ctrl.x},${r.ctrl.y} ${r.end.x},${r.end.y}`);
      path.setAttribute("marker-end", "url(#arrow)");
      g.appendChild(path);

      const lbl = document.createElementNS(SVG_NS, "g");
      lbl.classList.add("lbl");
      if (g.classList.contains("long")) {
        lbl.classList.add("long");
      }
      const text = document.createElementNS(SVG_NS, "text");
      lbl.appendChild(text);

      const title = document.createElementNS(SVG_NS, "title");
      g.appendChild(title);
      path.addEventListener("click", () => select(biome.key));

      edgeLayer.appendChild(g);
      labelLayer.appendChild(lbl);
      const a = positions.get(biome.key);
      const b = positions.get(link.to);
      edges.push({
        from: biome.key,
        to: link.to,
        link,
        g,
        path,
        lbl,
        text,
        title,
        route: r,
        length: Math.hypot(b.cx - a.cx, b.cy - a.cy),
        labelWidth: 0,
      });
    }
  }

  function refreshEdges() {
    for (const e of edges) {
      const p = chance(e.link);
      e.path.style.strokeWidth = `${1.5 + 2.5 * p}`;
      e.text.textContent = pct(p);
      e.labelWidth = Math.ceil(e.text.getComputedTextLength()) + 4;
      const src = byKey.get(e.from);
      e.title.textContent = `${src.name} → ${byKey.get(e.to).name}: ${pct(e.link.p)} with no Map (${
        e.link.pExact
      }), ${pct(e.link.pOffered)} to be offered with a Map · ${rollText(e.link, src.links.length)}`;
    }
    placeLabels();
  }

  // ------------------------------------------------------------ focus / selection
  function applyFocus() {
    const focus = state.hovered ?? state.selected;
    const wantedHits = state.wantedHover
      ? new Set(wanted.find(w => w.key === state.wantedHover)?.spots.map(s => s.biome))
      : null;
    // A planned route lights up its cards (with the waves spent there) and the hops between them.
    const pathEdges = new Set();
    const pathLabels = new Map();
    if (state.path) {
      state.path.forEach((step, i) => {
        pathLabels.set(step.key, [...(pathLabels.get(step.key) ?? []), step.label]);
        if (i > 0) {
          pathEdges.add(`${state.path[i - 1].key}>${step.key}`);
        }
      });
    }
    map.classList.toggle("has-focus", focus != null || wantedHits != null || state.path != null);
    const neighbors = new Set([...(wantedHits ?? []), ...pathLabels.keys()]);
    for (const e of edges) {
      const out = (focus != null && e.from === focus) || pathEdges.has(`${e.from}>${e.to}`);
      const inc = focus != null && e.to === focus;
      e.g.classList.toggle("out", out);
      e.g.classList.toggle("in", inc);
      e.lbl.classList.toggle("out", out);
      e.lbl.classList.toggle("in", inc);
      if (out) {
        neighbors.add(e.to);
      }
      if (inc) {
        neighbors.add(e.from);
      }
    }
    // Highlighted labels should sit above the dimmed ones.
    for (const e of edges) {
      if (e.g.classList.contains("out") || e.g.classList.contains("in")) {
        labelLayer.appendChild(e.lbl);
      }
    }
    for (const [key, el] of nodeEls) {
      el.classList.toggle("selected", key === focus);
      el.classList.toggle("neighbor", neighbors.has(key));
      el.classList.toggle("wanted-hit", wantedHits?.has(key) ?? false);
      el.classList.toggle("on-path", pathLabels.has(key));
      el.querySelector(".stage").textContent = (pathLabels.get(key) ?? []).join(" · ");
    }
  }

  // ------------------------------------------------------------ wanted strip
  const wantedBox = $("#wanted");
  const cycle = new Map();

  function setWanted(keys, { focusInput = false } = {}) {
    wantedKeys = [...new Set(keys)].filter(k => catalog.has(k));
    rebuildWanted();
    try {
      localStorage.setItem("biome-map-wanted", JSON.stringify(wantedKeys));
    } catch {
      // storage unavailable; the URL hash still carries the list
    }
    state.wantedHover = null;
    state.path = null;
    state.planner.option = null;
    renderBadges();
    renderWantedStrip(focusInput);
    updateHash();
    applyFocus();
    renderPanel();
  }

  function renderBadges() {
    for (const [key, el] of nodeEls) {
      el.querySelector(".badges")?.remove();
      el.insertAdjacentHTML("beforeend", badgesHtml(key));
    }
  }

  /** Looks a typed name or species key up in the catalog. */
  function findSpecies(text) {
    const q = text.trim().toLowerCase();
    if (!q) {
      return null;
    }
    return (
      catalog.get(q.toUpperCase().replace(/[\s.'’-]+/g, "_"))
      ?? [...catalog.values()].find(s => s.name.toLowerCase() === q)
      ?? [...catalog.values()].find(s => s.name.toLowerCase().startsWith(q))
      ?? null
    );
  }

  function renderWantedStrip(focusInput = false) {
    const items = wanted
      .map(w => {
        const biomesHere = [...new Set(w.spots.map(s => s.biome))];
        const where = biomesHere.length ? biomesHere.map(k => byKey.get(k)?.name ?? k).join(", ") : "not in the wild";
        const title = biomesHere.length
          ? `${w.name}: ${spotSummary(w.spots)}`
          : `${w.name} is in no biome's wild pool — it has to be hatched from an egg`;
        return `<span class="wanted-entry">
          <button type="button" class="wanted-item${biomesHere.length ? "" : " none"}" data-species="${w.key}" title="${title}">
            <span class="chip">${iconHtml(w)}</span>
            <span class="wname">${w.name}</span>
            <span class="wwhere">${where}</span>
          </button>
          <button type="button" class="rm" data-remove="${w.key}" title="Remove ${w.name}" aria-label="Remove ${w.name}">×</button>
        </span>`;
      })
      .join("");
    wantedBox.innerHTML = `<div class="wanted-title">Wanted</div>${items}${
      wanted.length ? "" : `<span class="muted small">Nothing yet — add a Pokémon to see where it spawns.</span>`
    }
      <form class="add-wanted" id="add-wanted-form" autocomplete="off">
        <input id="add-wanted" list="species-options" placeholder="Add a Pokémon…" aria-label="Add a Pokémon to the wanted list">
        <datalist id="species-options">${[...catalog.values()].map(s => `<option value="${s.name}">`).join("")}</datalist>
        <button type="submit" class="btn">Add</button>
        <span class="add-msg" id="add-msg" aria-live="polite"></span>
      </form>
      <button type="button" class="btn small-btn" id="reset-wanted" title="Back to the default list">Reset</button>
      <button type="button" class="btn planner-btn" id="open-planner">Boss planner</button>`;

    $("#open-planner").addEventListener("click", () => openPlanner());
    $("#reset-wanted").addEventListener("click", () => setWanted(defaultWanted));
    const input = $("#add-wanted");
    const msg = $("#add-msg");
    $("#add-wanted-form").addEventListener("submit", e => {
      e.preventDefault();
      const species = findSpecies(input.value);
      if (!species) {
        msg.textContent = `No Pokémon called “${input.value.trim()}”`;
        return;
      }
      if (wantedKeys.includes(species.key)) {
        msg.textContent = `${species.name} is already on the list`;
        return;
      }
      setWanted([...wantedKeys, species.key], { focusInput: true });
    });
    input.addEventListener("input", () => {
      msg.textContent = "";
    });
    if (focusInput) {
      input.focus();
    }
    for (const btn of wantedBox.querySelectorAll("[data-remove]")) {
      btn.addEventListener("click", () => setWanted(wantedKeys.filter(k => k !== btn.dataset.remove)));
    }
    for (const btn of wantedBox.querySelectorAll(".wanted-item")) {
      const species = wanted.find(w => w.key === btn.dataset.species);
      const biomesHere = [...new Set(species.spots.map(s => s.biome))];
      btn.addEventListener("pointerenter", () => {
        state.wantedHover = species.key;
        applyFocus();
      });
      btn.addEventListener("pointerleave", () => {
        state.wantedHover = null;
        applyFocus();
      });
      btn.addEventListener("click", () => {
        if (biomesHere.length === 0 || suppressClick) {
          return;
        }
        // Repeated clicks walk through every biome the species appears in.
        const i = (cycle.get(species.key) ?? -1) + 1;
        cycle.set(species.key, i);
        select(biomesHere[i % biomesHere.length], { scroll: true });
      });
    }
  }
  renderWantedStrip();

  function wantedRowsHtml(entries, { showBiome } = {}) {
    return `<ul class="routes">${entries
      .map(({ species, spots, biome }) => {
        const key = biome?.key ?? spots[0].biome;
        return `<li><button type="button" class="route wanted-row" data-key="${key}">
          <span class="picon-box">${iconHtml(species, 2)}</span>
          <span class="rname">${species.name}</span>
          <span class="rpct small">${showBiome ? (biome?.name ?? "") : ""}</span>
          <span class="rmeta">${spots.map(s => `${tierText(s)} · ${timesText(s)}`).join("<br>")}</span>
        </button></li>`;
      })
      .join("")}</ul>`;
  }

  function setHover(key) {
    state.hovered = key;
    applyFocus();
  }

  function select(key, { scroll = false } = {}) {
    state.selected = key;
    if (key) {
      // Looking at a biome replaces whatever route was lit up.
      state.path = null;
      state.planner.option = null;
      state.panel = "info";
    }
    applyFocus();
    renderPanel();
    updateHash();
    if (scroll && key) {
      centerOn(key);
    }
    if (key && window.matchMedia?.("(max-width: 900px)").matches) {
      // Narrow layout stacks the panel under the map; bring the details into view.
      panel.scrollIntoView({ block: "start", behavior: "smooth" });
    }
  }

  /** Mirrors the selected biome and a non-default wanted list into the URL. */
  function updateHash() {
    const parts = [];
    if (state.selected) {
      parts.push(`b=${state.selected}`);
    }
    if (wantedKeys.join(",") !== defaultWanted.join(",")) {
      parts.push(`w=${wantedKeys.join(",")}`);
    }
    const hash = parts.length ? `#${parts.join("&")}` : "";
    if (location.hash === hash || (!hash && !location.hash)) {
      return;
    }
    try {
      history.replaceState(null, "", `${location.pathname}${location.search}${hash}`);
    } catch {
      // file:// pages can't rewrite history in some browsers; fall back to the plain hash.
      try {
        location.hash = hash;
      } catch {
        // A host that forbids that too just loses the deep link; the page itself is unaffected.
      }
    }
  }

  // ------------------------------------------------------------ side panel
  function renderPanel() {
    if (state.panel === "planner") {
      renderPlanner();
      return;
    }
    const biome = state.selected ? byKey.get(state.selected) : null;
    if (!biome) {
      panel.innerHTML = `
        <h2>How biome travel works</h2>
        <p>Every 10 waves (every 5 in Endless) the game moves you to a linked biome. Hover or click a biome on the map to see where it can lead and where it is reached from.</p>
        <h3>With no Map (the game picks)</h3>
        <p>Each side path marked <span class="badge">1 in N roll</span> is rolled on its own and kept with a 1‑in‑N chance; main paths are always kept. One of the kept paths is then chosen at random. The percentages on the map already fold both steps together.</p>
        <h3>With a <img class="pixel" src="assets/items/map.png" alt="" style="width:20px;height:20px;vertical-align:middle"> ${DATA.mapItem.name}</h3>
        <p>${DATA.mapItem.description} You choose among the kept paths, so the numbers become the chance each destination is <em>offered</em>. Switch the toggle in the header to see them.</p>
        <h3>Reading the map</h3>
        <p><span class="badge">solid</span> always an option · <span class="badge">dashed</span> must win its roll first. Thicker lines are likelier. Drag to pan, scroll to zoom.</p>
        ${wanted.length ? wantedIntroHtml() : ""}
        <p class="muted">${biomes.length} biomes · ${edges.length} links · generated ${DATA.generatedAt.slice(0, 10)}</p>`;
      bindPanelRoutes();
      return;
    }

    const outs = biome.links.map(link => ({ biome: byKey.get(link.to), link, cls: "out", count: biome.links.length }));
    const ins = incoming(biome.key).map(({ from, link }) => ({ biome: from, link, cls: "in", count: from.links.length }));

    const routeHtml = ({ biome: other, link, cls, count }) => {
      const p = chance(link);
      const sure = count === 1 || (state.mode === "map" && link.weight === 1);
      return `
        <li><button type="button" class="route ${cls}" data-key="${other.key}">
          <img class="pixel" src="${other.art.bg ?? ""}" alt="">
          <span class="rname">${other.name}</span>
          <span class="rpct">${pct(p)}</span>
          <span class="bar"><i style="width:${(p * 100).toFixed(1)}%"></i></span>
          <span class="rmeta">${state.mode === "map" ? "" : `exact ${link.pExact} · `}<span class="badge${
            sure ? " sure" : ""
          }">${rollText(link, count)}</span></span>
        </button></li>`;
    };

    // Everything that can show up as this biome's boss, by tier, with the tier's roll odds.
    const bossTiers = ["BOSS", "BOSS_RARE", "BOSS_SUPER_RARE", "BOSS_ULTRA_RARE"];
    const bossHtml = bossTiers
      .map(tier => {
        const byTime = biome.pool?.[tier];
        if (!byTime) {
          return "";
        }
        const entries = new Map();
        for (const [time, list] of Object.entries(byTime)) {
          for (const key of list) {
            entries.set(key, [...(entries.get(key) ?? []), time]);
          }
        }
        // Effective share of the boss roll after downgrades, per time of day (luck 0).
        const shares = TIMES.map(time => effectiveTier(biome.pool, tier, time, 0));
        const den = shares[0].den;
        const nums = shares.map(s => s.num);
        const share = Math.min(...nums) === Math.max(...nums) ? `${fmtShare(nums[0])}/${den}` : `${fmtShare(Math.min(...nums))}–${fmtShare(Math.max(...nums))}/${den}`;
        const raw = DATA.tierChance?.[tier];
        const boosted = raw && Math.max(...nums) > raw[0];
        const chips = [...entries]
          .map(([key, times]) => {
            const species = catalog.get(key);
            if (!species) {
              return "";
            }
            const when = times.includes("ALL") ? "" : ` (${times.map(labelOf).join(", ")})`;
            const isWanted = wantedKeys.includes(key);
            return `<button type="button" class="boss-chip${isWanted ? " wanted" : ""}" data-add="${key}" title="${species.name}${when}${
              isWanted ? " · on your wanted list" : " · click to add to wanted"
            }">${iconHtml(species)}<span>${species.name}${when ? `<small>${when.trim()}</small>` : ""}</span></button>`;
          })
          .join("");
        return `<div class="boss-tier"><div class="boss-tier-head">${labelOf(tier)} <span class="muted" title="${
          boosted ? `${raw[0]}/${raw[1]} own roll, plus the share of rarer tiers that are empty here` : "share of the boss-wave tier roll"
        }">${share}${boosted ? " ↓" : ""}</span></div><div class="boss-chips">${chips}</div></div>`;
      })
      .join("");

    const endNote =
      biome.key === "END"
        ? `<p>The final biome. Classic runs are sent here for waves 191–200, Daily runs for wave 50. In Endless it comes around every 50 waves, and since it links nowhere the next biome is rolled at random.</p>`
        : "";

    panel.innerHTML = `
      <div class="arena pixel">${
        biome.art.bg
          ? `<img src="${biome.art.bg}" alt="">${biome.art.b ? `<img src="${biome.art.b}" alt="">` : ""}${
              biome.art.a ? `<img src="${biome.art.a}" alt="">` : ""
            }`
          : ""
      }</div>
      <h2>${biome.name}</h2>
      <dl class="facts">
        <dt>Earliest wave</dt><dd>${earliestWave(biome)}</dd>
        <dt>Trainer battles</dt><dd>${biome.trainerChance ? `1 in ${biome.trainerChance} waves` : "none"}</dd>
        <dt>Exits</dt><dd>${biome.links.length || "none"}</dd>
      </dl>
      ${endNote}
      <div class="actions">
        <button type="button" class="btn" id="center-btn">Center on map</button>
        <button type="button" class="btn" id="clear-btn">Clear</button>
        ${wanted.length && biome.key !== "END" ? `<button type="button" class="btn" id="here-btn" title="Plan boss waves from this biome">I'm here</button>` : ""}
      </div>
      ${
        wantedByBiome.has(biome.key)
          ? `<h3>Wanted here</h3>${wantedRowsHtml(wantedByBiome.get(biome.key))}
             <p class="muted small">Boss tiers only roll on boss waves (every 10th wave). Cards on the map carry the same icons.</p>`
          : ""
      }
      <h3>Leads to <span class="muted">(${state.mode === "map" ? "chance to be offered" : "chance with no Map"})</span></h3>
      ${outs.length ? `<ul class="routes">${outs.map(routeHtml).join("")}</ul>` : `<p class="muted">Nowhere — see above.</p>`}
      <h3>Reached from</h3>
      ${ins.length ? `<ul class="routes">${ins.map(routeHtml).join("")}</ul>` : `<p class="muted">No biome links here${biome.key === "TOWN" ? " — every run starts in Town" : ""}.</p>`}
      ${
        bossHtml
          ? `<h3>Bosses <span class="muted">(boss waves)</span></h3>
             <p class="muted small">The tier is rolled first (odds at luck 0), then one Pokémon from that tier for the current time of day. A roll on a tier that is empty here drops to the next filled tier (marked ↓), so the shares always add up to 64/64. Click a Pokémon to add it to your wanted list.</p>
             ${bossHtml}`
          : ""
      }`;

    bindPanelRoutes();
    for (const btn of panel.querySelectorAll(".boss-chip[data-add]")) {
      btn.addEventListener("click", () => {
        if (!wantedKeys.includes(btn.dataset.add)) {
          setWanted([...wantedKeys, btn.dataset.add]);
        }
      });
    }
    $("#center-btn").addEventListener("click", () => centerOn(biome.key));
    $("#clear-btn").addEventListener("click", () => select(null));
    $("#here-btn")?.addEventListener("click", () => openPlanner({ biome: biome.key }));
  }

  // ------------------------------------------------------------ boss planner
  // Classic mode: the biome changes after every wave ending in 0, so stretch t
  // covers waves 10t-9 … 10t and its boss (the wild boss, unless a gym leader
  // or the champion takes the slot) is wave 10t. Reaching biome T on boss wave
  // 10t therefore means walking exactly t - s links from the current biome,
  // where s is the current stretch. The search keeps, for every hop count and
  // every biome, the most likely way to get there under the current odds mode.
  const LAST_STRETCH = 18; // wave 190 is the champion, 191+ is the final biome
  const classic = DATA.classic ?? { fixedBattleWaves: [], gymWaves: { 20: [], 30: [] } };

  /**
   * The stretches ahead for the planner's mode.
   *
   * Classic: 10-wave stretches, boss on every wave ending in 0, gym leaders
   * and the champion block some of them, and the plan runs to wave 180.
   *
   * Endless: `hasShortBiomes` moves you every 5 waves, so only every other
   * stretch ends on a boss wave; every wave is wild (no trainers, no fixed
   * battles); after wave 49 (99, 149, …) the game forces the End biome for the
   * wave ending in 50, and End has no links, so the biome after it is random.
   * The plan therefore runs to the stretch just before the next End.
   */
  function schedule() {
    const { wave, gym, endless } = state.planner;
    if (endless) {
      const L = 5;
      const inEnd = wave % 50 === 0;
      const nextEnd = inEnd ? wave + 50 : Math.ceil(wave / 50) * 50;
      return {
        L,
        s: Math.ceil(wave / L),
        S: nextEnd / L - 1,
        nextEnd,
        inEnd,
        bossWaveOf: t => ((L * t) % 10 === 0 ? L * t : null),
        blocked: () => false,
        gymSet: new Set(),
      };
    }
    const gymSet = new Set(classic.gymWaves[gym] ?? []);
    const blockedSet = new Set([...gymSet, ...classic.fixedBattleWaves]);
    return {
      L: 10,
      s: Math.ceil(wave / 10),
      S: LAST_STRETCH,
      nextEnd: null,
      inEnd: false,
      bossWaveOf: t => 10 * t,
      blocked: w => blockedSet.has(w),
      gymSet,
    };
  }
  const stretchLabel = (sch, t) => `${sch.L * t - (sch.L - 1)}–${sch.L * t}`;

  function openPlanner(patch = {}) {
    Object.assign(state.planner, patch, { option: null });
    state.panel = "planner";
    state.selected = null;
    state.path = null;
    savePlanner();
    applyFocus();
    renderPanel();
  }

  const clampLuck = v => Math.min(14, Math.max(0, Math.round(Number(v) || 0)));
  const clampLures = v => Math.min(3, Math.max(0, Math.round(Number(v) || 0)));

  // Double battles: BattleScene.getDoubleBattleChance rolls 1-in-32 on a wave
  // ending in 0 (1-in-8 otherwise), every active lure divides that by 4, and
  // the result is clamped to at least 1 (a certain double). In a double both
  // enemies roll their species independently, so a double is two draws.
  const doubleChance = (boss, lures = state.planner.lures) => 1 / Math.max((boss ? 32 : 8) / 4 ** lures, 1);
  const doubleText = (boss, lures = state.planner.lures) => {
    const d = doubleChance(boss, lures);
    return d >= 1 ? "always" : `1 in ${Math.round(1 / d)}`;
  };
  /** Chance of hitting something with single-draw odds `p` when a double gives two draws. */
  const withDouble = (p, boss, lures = state.planner.lures) => {
    const d = doubleChance(boss, lures);
    return (1 - d) * p + d * (1 - (1 - p) ** 2);
  };

  // The shop's luck readout: getLuckString / getLuckTextTint in the game, with
  // the modifier-tier colours from getModifierTierTextTint and the rainbow
  // tint at 14.
  const LUCK_GRADES = ["D", "C", "C+", "B-", "B", "B+", "A-", "A", "A+", "A++", "S", "S+", "SS", "SS+", "SSS"];
  const luckTint = luck =>
    luck > 11 ? "#e74c18" : luck > 9 ? "#e331c5" : luck > 5 ? "#db4343" : luck > 2 ? "#f8d038" : luck ? "#4998f8" : "#f8f8f8";
  const luckHtml = luck =>
    luck >= 14
      ? `<span class="luck-grade rainbow">${LUCK_GRADES[14]}</span>`
      : `<span class="luck-grade" style="color:${luckTint(luck)}">${LUCK_GRADES[luck] ?? luck}</span>`;

  function savePlanner() {
    try {
      const { wave, biome, gym, luck, lures, endless } = state.planner;
      localStorage.setItem("biome-map-planner", JSON.stringify({ wave, biome, gym, luck, lures, endless }));
    } catch {
      // storage unavailable; nothing to do
    }
  }

  function loadPlanner() {
    try {
      const saved = JSON.parse(localStorage.getItem("biome-map-planner") ?? "null");
      if (saved && byKey.has(saved.biome) && Number.isFinite(saved.wave)) {
        Object.assign(state.planner, {
          wave: saved.wave,
          biome: saved.biome,
          gym: String(saved.gym) === "30" ? "30" : "20",
          luck: clampLuck(saved.luck),
          lures: clampLures(saved.lures),
          endless: saved.endless === true,
        });
      }
    } catch {
      // ignore bad or missing storage
    }
  }

  // Luck (shiny variant + 1 per shiny party member, capped at 14) does not move
  // the tier thresholds; it shrinks the roll range instead — Arena.randomSpecies
  // rolls over 64 - luck/2 values for a boss and 512 - 2*luck otherwise — so the
  // rare tiers at the bottom of the range get a little likelier.
  const tierDenominator = (den, luck) => den - luck * (den === 64 ? 0.5 : 2);

  // Tier roll, after the game's empty-tier downgrade. Arena.randomSpecies rolls a
  // tier, then while that tier's live pool (ALL + current time of day) is empty
  // it steps down one tier, so an empty rarer tier hands its whole share to the
  // next filled tier below it. Boss waves roll the four boss tiers (and only use
  // the ordinary roll instead when the Boss tier itself is empty at that time).
  const TIER_ORDER = ["COMMON", "UNCOMMON", "RARE", "SUPER_RARE", "ULTRA_RARE", "BOSS", "BOSS_RARE", "BOSS_SUPER_RARE", "BOSS_ULTRA_RARE"];
  const livePoolSize = (pool, tier, time) => new Set([...(pool?.[tier]?.ALL ?? []), ...(pool?.[tier]?.[time] ?? [])]).size;
  /** Raw share of the roll range for a tier; the top tier absorbs the luck-shrunk range. */
  function rawTierCount(tier, luck) {
    const boss = TIER_ORDER.indexOf(tier) >= 5;
    const range = tierDenominator(boss ? 64 : 512, luck);
    return (
      boss
        ? { BOSS: range - 20, BOSS_RARE: 14, BOSS_SUPER_RARE: 5, BOSS_ULTRA_RARE: 1 }
        : { COMMON: range - 156, UNCOMMON: 124, RARE: 26, SUPER_RARE: 5, ULTRA_RARE: 1 }
    )[tier];
  }
  /** Effective {num, den} share of the roll that ends up on `tier` in this biome at `time`. */
  function effectiveTier(pool, tier, time, luck = 0) {
    const idx = TIER_ORDER.indexOf(tier);
    const boss = idx >= 5;
    const den = tierDenominator(boss ? 64 : 512, luck);
    if (idx < 0 || (boss && livePoolSize(pool, "BOSS", time) === 0)) {
      return { num: 0, den };
    }
    let carry = 0;
    for (let i = boss ? 8 : 4; i >= (boss ? 5 : 0); i--) {
      const mass = rawTierCount(TIER_ORDER[i], luck) + carry;
      const filled = livePoolSize(pool, TIER_ORDER[i], time) > 0;
      if (i === idx) {
        return { num: filled ? mass : 0, den };
      }
      carry = filled ? 0 : mass;
    }
    return { num: 0, den };
  }
  const fmtShare = n => (Number.isInteger(n) ? `${n}` : n.toFixed(1));

  /** Per-wave odds of a spot: effective tier roll × uniform draw from the live pool, with doubles giving a second draw. */
  function encounterOdds(spot, luck = state.planner.luck, lures = state.planner.lures) {
    const present = spot.times[0] === "ALL" ? TIMES : spot.times;
    const perTime = present
      .map(time => {
        const size = spot.poolSizes?.[time] ?? 0;
        const { num, den } = effectiveTier(spot.pool, spot.tier, time, luck);
        return size > 0 && num > 0 ? { p: withDouble(num / den / size, spot.boss, lures), num, den, size } : null;
      })
      .filter(Boolean);
    if (perTime.length === 0) {
      return null;
    }
    const lo = Math.min(...perTime.map(t => t.p));
    const hi = Math.max(...perTime.map(t => t.p));
    const nums = perTime.map(t => t.num);
    const sizes = perTime.map(t => t.size);
    const fmt = p => (p * 100 < 1 ? `${(p * 100).toFixed(2)}%` : pct(p));
    return {
      text: lo === hi ? fmt(hi) : `${fmt(lo)}–${fmt(hi)}`,
      detail: `${fmtShare(Math.min(...nums))}${Math.min(...nums) === Math.max(...nums) ? "" : `–${fmtShare(Math.max(...nums))}`}/${fmtShare(
        perTime[0].den,
      )} tier roll × 1/${Math.min(...sizes)}${Math.min(...sizes) === Math.max(...sizes) ? "" : `–1/${Math.max(...sizes)}`} pick, double ${doubleText(
        spot.boss,
        lures,
      )}`,
    };
  }

  function planRoutes() {
    const { biome } = state.planner;
    const sch = schedule();
    const { s, S } = sch;
    const bossWaves = [];
    for (let t = s; t <= S; t++) {
      const w = sch.bossWaveOf(t);
      if (w != null) {
        bossWaves.push({ t, wave: w, gym: sch.gymSet.has(w), blocked: sch.blocked(w) });
      }
    }
    // best[k] = Map(biome -> { p, prev }) for walks of exactly k hops.
    const best = [new Map([[biome, { p: 1, prev: null }]])];
    for (let k = 1; k <= S - s; k++) {
      const layer = new Map();
      for (const [from, rec] of best[k - 1]) {
        for (const link of byKey.get(from)?.links ?? []) {
          const p = rec.p * chance(link);
          if (p > 0 && p > (layer.get(link.to)?.p ?? 0)) {
            layer.set(link.to, { p, prev: from });
          }
        }
      }
      best.push(layer);
    }
    const walk = (k, target) => {
      const keys = [target];
      for (let j = k; j > 0; j--) {
        keys.unshift(best[j].get(keys[0]).prev);
      }
      return keys;
    };
    const plans = wanted.map(species => {
      const targets = [...new Set(species.spots.filter(sp => sp.boss).map(sp => sp.biome))];
      const options = [];
      for (const bw of bossWaves) {
        if (bw.blocked) {
          continue;
        }
        const k = bw.t - s;
        for (const target of targets) {
          const rec = best[k]?.get(target);
          if (!rec) {
            continue;
          }
          options.push({
            wave: bw.wave,
            hops: k,
            target,
            p: rec.p,
            keys: walk(k, target),
            early: bw.wave < species.minWave,
          });
        }
      }
      const bestP = Math.max(0, ...options.filter(o => !o.early).map(o => o.p));
      for (const o of options) {
        o.best = !o.early && o.p === bestP;
      }
      return { species, targets, options };
    });
    return { sch, s, bossWaves, plans };
  }

  function showRoute(option) {
    const sch = schedule();
    state.path = option.keys.map((key, j) => {
      const t = sch.s + j;
      return { key, label: j === option.hops ? `★${sch.bossWaveOf(t)}` : stretchLabel(sch, t) };
    });
    applyFocus();
    fitView();
  }

  /** Chance a boss wave in `biome` rolls one of `speciesList`, counting a double battle as two draws. */
  function hitOdds(speciesList, biome) {
    const single = speciesList.reduce((sum, sp) => sum + speciesOddsAt(sp, biome), 0);
    return withDouble(Math.min(single, 1), true);
  }

  /** Average single-draw odds of `species` rolling on a boss wave in `biome`, over the four times of day, at the planner's luck. */
  function speciesOddsAt(species, biome, luck = state.planner.luck) {
    let total = 0;
    for (const spot of species.spots) {
      if (spot.biome !== biome || !spot.boss) {
        continue;
      }
      // Average over the four times of day; the species contributes nothing at a time it is not in the pool.
      const present = spot.times[0] === "ALL" ? TIMES : spot.times;
      for (const time of present) {
        const size = spot.poolSizes?.[time] ?? 0;
        const { num, den } = effectiveTier(spot.pool, spot.tier, time, luck);
        if (size > 0) {
          total += (num / den / size) / TIMES.length;
        }
      }
    }
    return total;
  }

  const fmtChance = p => (p >= 0.01 ? pct(p) : p > 0 ? `1 in ${Math.round(1 / p).toLocaleString()}` : "0%");

  // Whole-run search: walk every remaining stretch and count the free boss
  // waves a route spends in a biome holding a wanted species (once that
  // species can roll). Each (stretch, biome) state keeps, for every hit count,
  // its few most likely routes (one per distinct set of hits) under the
  // current odds mode. That is exact per hit count: a prefix that is more
  // likely with the same hits stays more likely under the same continuation.
  // The result is the trade-off curve — for each number of boss waves, the
  // most likely way to get them — with dominated entries dropped.
  function bestFullRoutes({ perCount = 3, showPerCount = 2 } = {}) {
    const { biome } = state.planner;
    const sch = schedule();
    const { s, S, gymSet } = sch;
    const speciesAt = new Map();
    for (const species of wanted) {
      for (const spot of species.spots) {
        if (spot.boss) {
          if (!speciesAt.has(spot.biome)) {
            speciesAt.set(spot.biome, new Set());
          }
          speciesAt.get(spot.biome).add(species);
        }
      }
    }
    const hitAt = (key, t) => {
      const w = sch.bossWaveOf(t);
      if (w == null || sch.blocked(w)) {
        return null;
      }
      const list = [...(speciesAt.get(key) ?? [])].filter(sp => w >= sp.minWave);
      return list.length ? { wave: w, biome: key, species: list } : null;
    };
    const withHit = (route, key, t) => {
      const hit = hitAt(key, t);
      return hit
        ? {
            ...route,
            // reachProb: chance the route has held up to this boss wave.
            hits: [...route.hits, { ...hit, reachProb: route.prob }],
            sig: `${route.sig}${hit.wave}:${key};`,
            probAtLastHit: route.prob,
            lastHitIndex: route.keys.length - 1,
          }
        : route;
    };
    /** Best `limit` routes per hit count, one per distinct set of hits, most likely first. */
    const prune = (routes, limit) => {
      const byCount = new Map();
      for (const r of routes) {
        const bySig = byCount.get(r.hits.length) ?? new Map();
        if (!bySig.has(r.sig) || bySig.get(r.sig).prob < r.prob) {
          bySig.set(r.sig, r);
        }
        byCount.set(r.hits.length, bySig);
      }
      return [...byCount.values()].flatMap(bySig => [...bySig.values()].sort((a, b) => b.prob - a.prob).slice(0, limit));
    };

    let layer = new Map([[biome, [withHit({ keys: [biome], prob: 1, hits: [], sig: "", probAtLastHit: 1, lastHitIndex: -1 }, biome, s)]]]);
    for (let t = s + 1; t <= S; t++) {
      const next = new Map();
      for (const [from, routes] of layer) {
        for (const link of byKey.get(from)?.links ?? []) {
          const q = chance(link);
          if (q <= 0) {
            continue;
          }
          const bucket = next.get(link.to) ?? [];
          for (const r of routes) {
            bucket.push(withHit({ ...r, keys: [...r.keys, link.to], prob: r.prob * q }, link.to, t));
          }
          next.set(link.to, bucket);
        }
      }
      layer = new Map([...next].map(([key, routes]) => [key, prune(routes, perCount)]));
    }
    // Trade-off curve: most boss waves first; a route with fewer boss waves is
    // only worth listing when it is strictly more likely than everything above it.
    const candidates = prune(
      [...layer.values()].flat().filter(r => r.hits.length > 0),
      showPerCount,
    ).sort((a, b) => b.hits.length - a.hits.length || b.probAtLastHit - a.probAtLastHit);
    const routes = [];
    let bestAbove = 0; // most likely route among those with strictly more boss waves
    let bestInCount = 0;
    let currentCount = null;
    for (const r of candidates) {
      if (r.hits.length !== currentCount) {
        bestAbove = Math.max(bestAbove, bestInCount);
        bestInCount = 0;
        currentCount = r.hits.length;
      }
      if (r.probAtLastHit > bestAbove) {
        routes.push(r);
      }
      bestInCount = Math.max(bestInCount, r.probAtLastHit);
    }
    for (const r of routes) {
      // Chance of rolling at least one wanted Pokémon, counting the chance the
      // route breaks between boss waves (after a break, later hits are lost).
      let none = 1 - (r.hits[0]?.reachProb ?? 0);
      let missAll = 1;
      r.hits.forEach((h, i) => {
        const odds = hitOdds(h.species, h.biome);
        missAll *= 1 - odds;
        const holdsToNext = r.hits[i + 1]?.reachProb ?? 0;
        none += (h.reachProb - holdsToNext) * missAll;
      });
      r.atLeastOne = 1 - none;
      r.atLeastOneIfHeld = 1 - missAll;
    }
    const bestBet = Math.max(0, ...routes.map(r => r.atLeastOne));
    for (const r of routes) {
      r.bestBet = r.atLeastOne === bestBet;
    }
    // Safest first: the reader trades certainty for extra boss waves as they go down.
    routes.sort((a, b) => b.probAtLastHit - a.probAtLastHit || b.hits.length - a.hits.length);
    return { sch, s, gymSet, routes };
  }

  function showFullRoute(route, sch) {
    state.path = route.keys.slice(0, route.lastHitIndex + 1).map((key, j) => {
      const t = sch.s + j;
      const w = sch.bossWaveOf(t);
      const hit = w != null && route.hits.some(h => h.wave === w);
      return { key, label: hit ? `★${w}` : `${stretchLabel(sch, t)}${w != null && sch.gymSet.has(w) ? " gym" : ""}` };
    });
    applyFocus();
    fitView();
  }

  function renderPlanner() {
    const { wave, biome, gym, luck, lures, endless } = state.planner;
    const modeText = state.mode === "map" ? "odds you can steer that way with a Map" : "odds with no Map, when the game picks";
    const rules = endless
      ? "Endless mode. Biomes change after every 5th wave and every wave ending in 0 is a wild boss; there are no trainers, so nothing takes a boss slot. Every 50th wave is the End biome, and the biome after it is random, so the plan runs to the stretch before the next End. After wave 250 ordinary waves can also be bosses (2% per 50 waves past 250, up to 30%) — a bonus not counted here."
      : "Classic mode. Every wave ending in 0 is a boss, and after it you move to a linked biome. Gym leaders take the boss slot on their waves; the champion takes wave 190.";
    panel.innerHTML = `
      <div class="panel-head">
        <h2>Boss planner</h2>
        <button type="button" class="btn" id="planner-back">Back</button>
      </div>
      <p class="muted small">${rules} Only boss waves are planned here — a Pokémon that only appears on ordinary waves is listed but not routed. A boss wave is a double battle 1 in 32 times (lures raise that), and each Pokémon in a double rolls its species separately.</p>
      <form class="plan-form" id="plan-form">
        <fieldset>
          <legend>Mode</legend>
          <label><input type="radio" name="plan-endless" value="classic"${endless ? "" : " checked"}> Classic</label>
          <label><input type="radio" name="plan-endless" value="endless"${endless ? " checked" : ""}> Endless</label>
        </fieldset>
        <label>Wave <input type="number" id="plan-wave" min="1" max="${endless ? 9999 : 200}" value="${wave}"></label>
        <label>Biome <select id="plan-biome">${biomes
          .filter(b => b.key !== "END")
          .sort((a, b) => a.name.localeCompare(b.name))
          .map(b => `<option value="${b.key}"${b.key === biome ? " selected" : ""}>${b.name}</option>`)
          .join("")}</select></label>
        <fieldset id="plan-gym-set"${endless ? " hidden" : ""}>
          <legend>Gym leaders on</legend>
          <label><input type="radio" name="plan-gym" value="20"${gym === "20" ? " checked" : ""}> 20 · 50 · 80 …</label>
          <label><input type="radio" name="plan-gym" value="30"${gym === "30" ? " checked" : ""}> 30 · 60 · 90 …</label>
        </fieldset>
        <label title="Each shiny in your party adds its variant + 1 (a shiny fusion half adds the same again); the game caps it at 14">Luck <input type="number" id="plan-luck" min="0" max="14" value="${luck}"> <span class="luck-readout"><span class="luck-label">Luck:</span> <span id="plan-luck-grade">${luckHtml(luck)}</span></span></label>
        <label title="Lure, Super Lure and Max Lure each divide the double-battle roll by 4 while active; a double battle rolls two boss Pokémon">Lures <input type="number" id="plan-lures" min="0" max="3" value="${lures}"> <span class="muted small" id="plan-lures-note">boss wave doubles ${doubleText(true, lures)}</span></label>
      </form>
      <div id="plan-results"></div>`;
    $("#planner-back").addEventListener("click", () => {
      state.panel = "info";
      state.path = null;
      state.planner.option = null;
      applyFocus();
      renderPanel();
    });
    const update = () => {
      const isEndless = panel.querySelector("input[name=plan-endless]:checked")?.value === "endless";
      const w = Math.min(isEndless ? 9999 : 200, Math.max(1, Number($("#plan-wave").value) || 1));
      Object.assign(state.planner, {
        wave: w,
        biome: $("#plan-biome").value,
        gym: panel.querySelector("input[name=plan-gym]:checked")?.value ?? "20",
        luck: clampLuck($("#plan-luck").value),
        lures: clampLures($("#plan-lures").value),
        endless: isEndless,
        option: null,
      });
      state.path = null;
      savePlanner();
      applyFocus();
      if (isEndless !== endless) {
        // Mode changes the rules text and which inputs apply, so rebuild the whole panel.
        renderPlanner();
        return;
      }
      $("#plan-wave").value = state.planner.wave;
      $("#plan-luck").value = state.planner.luck;
      $("#plan-lures").value = state.planner.lures;
      $("#plan-lures-note").textContent = `boss wave doubles ${doubleText(true)}`;
      renderPlanResults();
    };
    for (const r of panel.querySelectorAll("input[name=plan-endless]")) {
      r.addEventListener("change", update);
    }
    $("#plan-wave").addEventListener("change", update);
    $("#plan-biome").addEventListener("change", update);
    $("#plan-luck").addEventListener("change", update);
    $("#plan-luck").addEventListener("input", () => {
      $("#plan-luck-grade").innerHTML = luckHtml(clampLuck($("#plan-luck").value));
    });
    $("#plan-lures").addEventListener("change", update);
    $("#plan-lures").addEventListener("input", () => {
      $("#plan-lures-note").textContent = `boss wave doubles ${doubleText(true, clampLures($("#plan-lures").value))}`;
    });
    for (const r of panel.querySelectorAll("input[name=plan-gym]")) {
      r.addEventListener("change", update);
    }
    renderPlanResults();

    function renderPlanResults() {
      const { sch, s, bossWaves, plans } = planRoutes();
      const out = $("#plan-results");
      const cur = byKey.get(state.planner.biome);
      const upcoming = bossWaves.filter(b => !b.blocked);
      if (sch.inEnd) {
        out.innerHTML = `<p>Wave ${state.planner.wave} is the End biome, and the biome after it is rolled at random. Come back once you land in it and enter that biome with wave ${state.planner.wave + 1}.</p>`;
        return;
      }
      if (upcoming.length === 0) {
        out.innerHTML = state.planner.endless
          ? `<p>No boss waves left before the End biome at wave ${sch.nextEnd}. The biome after it is random, so plan again once you are there.</p>`
          : `<p>No wild boss waves left after wave ${state.planner.wave}: 190 is the champion and 191–200 is the final biome.</p>`;
        return;
      }
      const routeHtml = (species, o, i) => {
        const names = o.keys.map(k => byKey.get(k).name);
        const active = state.planner.option === `${species.key}:${i}`;
        return `<li><button type="button" class="opt${o.early ? " early" : ""}${active ? " active" : ""}" data-opt="${species.key}:${i}">
          <span class="oname">Wave ${o.wave}${o.early ? ` <span class="badge">too early, rerolled before ${species.minWave}</span>` : o.best ? ` <span class="badge sure">best odds</span>` : ""}</span>
          <span class="opct">${pct(o.p)}</span>
          <span class="opath">${o.hops === 0 ? `stay in ${names[0]} for the boss` : names.join(" › ")}</span>
        </button></li>`;
      };
      const full = bestFullRoutes();
      const fullHtml = full.routes
        .map((r, i) => {
          const counts = new Map();
          for (const h of r.hits) {
            for (const sp of h.species) {
              counts.set(sp.name, (counts.get(sp.name) ?? 0) + 1);
            }
          }
          const chips = r.keys
            .slice(0, r.lastHitIndex + 1)
            .map((key, j) => {
              const t = full.s + j;
              const w = full.sch.bossWaveOf(t);
              const hit = w != null && r.hits.some(h => h.wave === w);
              const gymHere = w != null && full.gymSet.has(w);
              return `<span class="rc${hit ? " hit" : gymHere ? " gym" : ""}" title="waves ${stretchLabel(full.sch, t)}${
                hit ? ", wild boss with a wanted Pokémon" : gymHere ? ", gym leader" : w == null ? ", no boss wave" : ""
              }">${byKey.get(key).name}<small>${w ?? stretchLabel(full.sch, t)}</small></span>`;
            })
            .join("");
          const active = state.planner.option === `full:${i}`;
          return `<li><button type="button" class="opt${active ? " active" : ""}" data-full="${i}">
            <span class="oname">${r.hits.length} boss wave${r.hits.length === 1 ? "" : "s"}${r.bestBet ? ` <span class="badge sure">best bet</span>` : ""} <span class="muted">· ${[...counts].map(([n, c]) => `${n} ×${c}`).join(", ")}</span></span>
            <span class="opct" title="chance of holding this route through its last wanted boss wave">${fmtChance(r.probAtLastHit)}</span>
            <span class="opath rchips">${chips}</span>
            <span class="opath">≈ ${fmtChance(r.atLeastOne)} to roll at least one of them overall (${pct(r.atLeastOneIfHeld)} if the route holds)</span>
          </button></li>`;
        })
        .join("");
      const isEndless = state.planner.endless;
      out.innerHTML = `
        <p class="small">From <b>${cur?.name ?? "?"}</b> on wave ${state.planner.wave} (stretch ${stretchLabel(sch, s)}). ${
          isEndless ? `Boss waves before the End at wave ${sch.nextEnd}:` : "Wild boss waves ahead:"
        }</p>
        <div class="wave-chips">${bossWaves
          .map(b => `<span class="wave-chip${b.gym ? " gym" : b.blocked ? " gym" : ""}" title="${b.gym ? "gym leader" : b.blocked ? "fixed battle" : "wild boss"}">${b.wave}</span>`)
          .join("")}${isEndless ? `<span class="wave-chip end" title="End biome; the biome after it is random">End ${sch.nextEnd}</span>` : ""}</div>
        <p class="muted small">Percentages are the ${modeText}, multiplied along the route. Click a route to draw it on the map.${
          isEndless ? "" : " Not sure which gym set you have? The first gym leader is on wave 20 or 30."
        }</p>
        <h3>Best full routes</h3>
        <p class="muted small">${
          isEndless
            ? `Routes up to the End biome at wave ${sch.nextEnd}, safest first.`
            : "Whole-run routes to wave 180, safest first."
        } For each number of wanted boss waves this is the most likely way to get them, and a route only makes the list if it is more likely than every route with more boss waves. The big number is the chance of holding the route; “best bet” has the highest overall chance of an actual catch.${
          isEndless ? "" : " Gym leaders repeat every 3 stretches, so 3-biome loops can keep the gym out of the way."
        }</p>
        ${full.routes.length ? `<ul class="routes">${fullHtml}</ul>` : `<p class="muted small">No free boss wave in a wanted biome is reachable from here.</p>`}
        <h3>One target at a time</h3>
        ${plans
          .map(({ species, targets, options }) => {
            const spots = species.spots.filter(sp => targets.includes(sp.biome) && sp.boss);
            const odds = spots.map(sp => encounterOdds(sp)).filter(Boolean);
            const ordinaryBiomes = [...new Set(species.spots.filter(sp => !sp.boss).map(sp => byKey.get(sp.biome)?.name ?? sp.biome))];
            const head = `<div class="species-head"><span class="picon-box inline">${iconHtml(species, 2)}</span>
              <div><div class="sname">${species.name}</div>
              <div class="muted small">${
                targets.map(k => byKey.get(k).name).join(", ") || (ordinaryBiomes.length ? "never a boss" : "not in the wild")
              }${
                odds.length
                  ? ` · ${odds.map(o => o.text).join(" / ")} per boss wave there${state.planner.luck ? ` at ${luckHtml(state.planner.luck)} luck` : ""}${
                      state.planner.lures ? ` with ${state.planner.lures} lure${state.planner.lures === 1 ? "" : "s"}` : ""
                    }`
                  : ""
              }${
                species.minWave > 1 ? ` · from wave ${species.minWave}` : ""
              }</div></div></div>`;
            if (targets.length === 0) {
              return `${head}<p class="muted small">${
                ordinaryBiomes.length
                  ? `Only appears on ordinary wild waves (${ordinaryBiomes.join(", ")}), never as a boss, so the boss planner has nothing to plan for it. Click the biome on the map for its odds there.`
                  : "Not in any biome's wild pool — it has to be hatched from an egg."
              }</p>`;
            }
            const shown = options.filter(o => !o.early || o.wave === options[0]?.wave).slice(0, 8);
            const wild = species.spots
              .filter(sp => !sp.boss && targets.includes(sp.biome))
              .map(sp => encounterOdds(sp))
              .filter(Boolean);
            return `${head}${
              shown.length
                ? `<ul class="routes">${shown.map((o, i) => routeHtml(species, o, options.indexOf(o))).join("")}</ul>`
                : `<p class="muted small">No route reaches ${targets.map(k => byKey.get(k).name).join(" or ")} on a free boss wave from here.</p>`
            }${wild.length ? `<p class="muted small">Also ${wild.map(o => o.text).join(" / ")} on any ordinary wild wave there.</p>` : ""}`;
          })
          .join("")}`;
      for (const btn of out.querySelectorAll(".opt[data-full]")) {
        btn.addEventListener("click", () => {
          const route = full.routes[Number(btn.dataset.full)];
          state.planner.option = `full:${btn.dataset.full}`;
          for (const b of out.querySelectorAll(".opt")) {
            b.classList.toggle("active", b === btn);
          }
          showFullRoute(route, full.sch);
        });
      }
      for (const btn of out.querySelectorAll(".opt[data-opt]")) {
        btn.addEventListener("click", () => {
          const [key, idx] = btn.dataset.opt.split(":");
          const plan = plans.find(p => p.species.key === key);
          const option = plan?.options[Number(idx)];
          if (!option) {
            return;
          }
          state.planner.option = btn.dataset.opt;
          for (const b of out.querySelectorAll(".opt")) {
            b.classList.toggle("active", b === btn);
          }
          showRoute(option);
        });
      }
    }
  }

  function bindPanelRoutes() {
    panel.querySelectorAll(".route").forEach(btn => {
      btn.addEventListener("click", () => select(btn.dataset.key, { scroll: true }));
      btn.addEventListener("pointerenter", () => setHover(btn.dataset.key));
      btn.addEventListener("pointerleave", () => setHover(null));
    });
  }

  function wantedIntroHtml() {
    const found = [];
    const missing = [];
    for (const species of wanted) {
      const biomesHere = [...new Set(species.spots.map(s => s.biome))];
      if (biomesHere.length === 0) {
        missing.push(species);
        continue;
      }
      for (const key of biomesHere) {
        found.push({ species, biome: byKey.get(key), spots: species.spots.filter(s => s.biome === key) });
      }
    }
    return `<h3>Wanted</h3>
      ${found.length ? wantedRowsHtml(found, { showBiome: true }) : ""}
      ${missing
        .map(
          species =>
            `<p class="muted"><span class="picon-box inline">${iconHtml(species, 2)}</span> ${species.name} is in no biome's wild pool — it has to be hatched from an egg.</p>`,
        )
        .join("")}`;
  }

  // ------------------------------------------------------------ table
  function renderTable() {
    const rows = [];
    for (const biome of biomes) {
      biome.links.forEach((link, i) => {
        const target = byKey.get(link.to);
        rows.push(`<tr class="${i === 0 ? "first" : ""}">
          <td class="src">${i === 0 ? `<a class="jump" href="#${biome.key}"><img class="pixel" src="${biome.art.bg ?? ""}" alt="">${biome.name}</a>` : ""}</td>
          <td><a class="jump" href="#${target.key}"><img class="pixel" src="${target.art.bg ?? ""}" alt="">${target.name}</a></td>
          <td class="num">${pct(link.p)}</td>
          <td class="num">${link.pExact}</td>
          <td class="num">${pct(link.pOffered)}</td>
          <td>${rollText(link, biome.links.length)}</td>
        </tr>`);
      });
    }
    tableBody.innerHTML = rows.join("");
  }

  // ------------------------------------------------------------ pan & zoom
  function applyView() {
    const { x, y, k } = state.view;
    map.style.transform = `translate(${x}px, ${y}px) scale(${k})`;
  }

  function fitView() {
    const vw = viewport.clientWidth;
    const vh = viewport.clientHeight;
    if (vw === 0 || vh === 0) {
      // Not laid out yet (e.g. embedded in a frame that is still hidden); the
      // ResizeObserver below fits the map once it has a size.
      return;
    }
    const k = Math.min(vw / MAP_W, vh / MAP_H, 1.4) * 0.97;
    state.view = { k, x: (vw - MAP_W * k) / 2, y: (vh - MAP_H * k) / 2 };
    applyView();
  }

  function zoomBy(factor, px = viewport.clientWidth / 2, py = viewport.clientHeight / 2) {
    const v = state.view;
    const k2 = Math.min(3, Math.max(0.25, v.k * factor));
    v.x = px - (px - v.x) * (k2 / v.k);
    v.y = py - (py - v.y) * (k2 / v.k);
    v.k = k2;
    applyView();
  }

  function centerOn(key) {
    const p = positions.get(key);
    const v = state.view;
    if (v.k < 0.85) {
      v.k = 1;
    }
    v.x = viewport.clientWidth / 2 - p.cx * v.k;
    v.y = viewport.clientHeight / 2 - p.cy * v.k;
    applyView();
  }

  // Drag-to-pan. Deliberately no pointer capture: some browsers deliver the
  // `click` to the capturing element instead of the card under the pointer,
  // which would swallow card clicks. Moves and the release are tracked on
  // `window` instead so a drag that leaves the map still ends cleanly.
  let suppressClick = false;
  let drag = null;
  const onDragMove = e => {
    if (!drag || e.pointerId !== drag.id) {
      return;
    }
    const dx = e.clientX - drag.sx;
    const dy = e.clientY - drag.sy;
    if (!drag.moved && Math.hypot(dx, dy) > 4) {
      drag.moved = true;
      viewport.classList.add("dragging");
    }
    if (drag.moved) {
      state.view.x = drag.ox + dx;
      state.view.y = drag.oy + dy;
      applyView();
    }
  };
  const endDrag = e => {
    if (!drag || (e && e.pointerId !== drag.id)) {
      return;
    }
    if (drag.moved) {
      // The click that follows a drag must not select whatever card it lands on.
      suppressClick = true;
      setTimeout(() => {
        suppressClick = false;
      }, 0);
    }
    drag = null;
    viewport.classList.remove("dragging");
    window.removeEventListener("pointermove", onDragMove);
    window.removeEventListener("pointerup", endDrag);
    window.removeEventListener("pointercancel", endDrag);
  };
  viewport.addEventListener("pointerdown", e => {
    if (e.button !== 0 || drag) {
      return;
    }
    drag = { id: e.pointerId, sx: e.clientX, sy: e.clientY, ox: state.view.x, oy: state.view.y, moved: false };
    window.addEventListener("pointermove", onDragMove);
    window.addEventListener("pointerup", endDrag);
    window.addEventListener("pointercancel", endDrag);
  });
  viewport.addEventListener(
    "wheel",
    e => {
      e.preventDefault();
      const rect = viewport.getBoundingClientRect();
      zoomBy(Math.exp(-e.deltaY * 0.0012), e.clientX - rect.left, e.clientY - rect.top);
    },
    { passive: false },
  );

  // ------------------------------------------------------------ controls
  $("#zoom-in").addEventListener("click", () => zoomBy(1.25));
  $("#zoom-out").addEventListener("click", () => zoomBy(0.8));
  $("#zoom-fit").addEventListener("click", fitView);

  for (const btn of document.querySelectorAll("[data-mode]")) {
    btn.addEventListener("click", () => {
      state.mode = btn.dataset.mode;
      for (const b of document.querySelectorAll("[data-mode]")) {
        b.setAttribute("aria-pressed", String(b === btn));
      }
      refreshEdges();
      renderPanel();
    });
  }

  $("#toggle-labels").addEventListener("click", e => {
    state.showLabels = !state.showLabels;
    e.currentTarget.setAttribute("aria-pressed", String(state.showLabels));
    map.classList.toggle("show-labels", state.showLabels);
  });

  window.addEventListener("hashchange", () => {
    const { b, w } = parseHash();
    if (w && w.join(",") !== wantedKeys.join(",")) {
      setWanted(w);
    }
    if (b && byKey.has(b) && b !== state.selected) {
      select(b, { scroll: true });
    }
  });

  window.addEventListener("resize", fitView);
  // Embedded pages (the artifact viewer, for one) start out hidden, so the
  // first real size arrives after boot: fit the map and re-measure the labels then.
  if (typeof ResizeObserver === "function") {
    let hadSize = viewport.clientWidth > 0 && viewport.clientHeight > 0;
    new ResizeObserver(() => {
      const hasSize = viewport.clientWidth > 0 && viewport.clientHeight > 0;
      if (hasSize && !hadSize) {
        refreshEdges();
        fitView();
      }
      hadSize = hasSize;
    }).observe(viewport);
  }

  // ------------------------------------------------------------ boot
  map.classList.add("show-labels");
  loadPlanner();
  renderTable();
  refreshEdges();
  renderPanel();
  fitView();
  const initial = parseHash().b;
  if (initial && byKey.has(initial)) {
    select(initial, { scroll: true });
  } else {
    updateHash();
  }
  // Labels are measured with the fallback font first; redo them once the pixel font is in.
  document.fonts?.load("14px emerald").then(refreshEdges, () => {});
})();
